# Generated by Django 3.2.7 on 2021-09-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
