# Generated by Django 3.2.7 on 2021-09-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_survey_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logins',
        ),
    ]
